import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/index',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/intro',
        {
          type: 'category',
          label: 'Backend API',
          items: [
            'api/backend/intro',
          ],
        },
        {
          type: 'category',
          label: 'Frontend API',
          link: {
            type: 'doc',
            id: 'api/frontend/README',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/frontend',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'User Guides',
      items: [
        'guides/intro',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/intro',
      ],
    },
  ],
};

export default sidebars;
