"""Pydantic schemas package"""

from app.schemas.market import (
    ActiveStock,
    MarketBreadthResponse,
    MarketIndexData,
    MarketIndicesResponse,
    MarketMover,
    MarketMoversResponse,
    MarketTrendData,
    MarketTrendResponse,
    MostActiveResponse,
    SectorPerformance,
    SectorPerformanceResponse,
    TopStock,
)
from app.schemas.portfolio import (
    HoldingCreate,
    HoldingListResponse,
    HoldingResponse,
    HoldingUpdate,
    PortfolioAllocation,
    PortfolioCreate,
    PortfolioListResponse,
    PortfolioPerformance,
    PortfolioResponse,
    PortfolioSummary,
    PortfolioUpdate,
    TransactionCreate,
    TransactionListResponse,
    TransactionResponse,
    TransactionType,
)
from app.schemas.screening import (FilterRange, ScreenedStock,
                                   ScreeningFilters, ScreeningMetadata,
                                   ScreeningRequest, ScreeningResponse,
                                   ScreeningTemplate, ScreeningTemplateList)
from app.schemas.stock import (CalculatedIndicator, DailyPrice,
                               DailyPriceListResponse, DailyPriceWithChanges,
                               FinancialStatement,
                               FinancialStatementListResponse,
                               FinancialStatementWithRatios, PaginationMeta,
                               Stock, StockDetail, StockListItem,
                               StockListResponse, StockSearchQuery,
                               StockSearchResponse, StockSearchResult)
from app.schemas.user import (EmailVerificationRequest, PasswordResetConfirm,
                              PasswordResetRequest, RefreshTokenRequest,
                              SuccessResponse, TokenPayload, TokenResponse,
                              UserCreate, UserLogin, UserResponse, UserUpdate,
                              VerificationStatusResponse)
from app.schemas.watchlist import (
    DashboardSummary,
    ScreeningQuota,
    UserActivityCreate,
    UserActivityListResponse,
    UserActivityResponse,
    UserPreferencesCreate,
    UserPreferencesResponse,
    UserPreferencesUpdate,
    WatchlistCreate,
    WatchlistListResponse,
    WatchlistResponse,
    WatchlistStockCreate,
    WatchlistStockResponse,
    WatchlistSummary,
    WatchlistUpdate,
)

__all__ = [
    # User schemas
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserUpdate",
    "TokenPayload",
    "TokenResponse",
    "RefreshTokenRequest",
    "EmailVerificationRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "VerificationStatusResponse",
    "SuccessResponse",
    # Stock schemas
    "Stock",
    "StockDetail",
    "StockListItem",
    "StockListResponse",
    "DailyPrice",
    "DailyPriceWithChanges",
    "DailyPriceListResponse",
    "FinancialStatement",
    "FinancialStatementWithRatios",
    "FinancialStatementListResponse",
    "CalculatedIndicator",
    "PaginationMeta",
    "StockSearchQuery",
    "StockSearchResult",
    "StockSearchResponse",
    # Market schemas
    "MarketIndexData",
    "MarketIndicesResponse",
    "MarketBreadthResponse",
    "TopStock",
    "SectorPerformance",
    "SectorPerformanceResponse",
    "MarketMover",
    "MarketMoversResponse",
    "ActiveStock",
    "MostActiveResponse",
    "MarketTrendData",
    "MarketTrendResponse",
    # Screening schemas
    "FilterRange",
    "ScreeningFilters",
    "ScreeningRequest",
    "ScreenedStock",
    "ScreeningMetadata",
    "ScreeningResponse",
    "ScreeningTemplate",
    "ScreeningTemplateList",
    # Watchlist schemas
    "WatchlistCreate",
    "WatchlistUpdate",
    "WatchlistResponse",
    "WatchlistSummary",
    "WatchlistListResponse",
    "WatchlistStockCreate",
    "WatchlistStockResponse",
    # User Activity schemas
    "UserActivityCreate",
    "UserActivityResponse",
    "UserActivityListResponse",
    # Dashboard schemas
    "DashboardSummary",
    "ScreeningQuota",
    # User Preferences schemas
    "UserPreferencesCreate",
    "UserPreferencesUpdate",
    "UserPreferencesResponse",
    # Portfolio schemas
    "PortfolioCreate",
    "PortfolioUpdate",
    "PortfolioResponse",
    "PortfolioListResponse",
    "PortfolioSummary",
    "PortfolioPerformance",
    "PortfolioAllocation",
    # Holding schemas
    "HoldingCreate",
    "HoldingUpdate",
    "HoldingResponse",
    "HoldingListResponse",
    # Transaction schemas
    "TransactionType",
    "TransactionCreate",
    "TransactionResponse",
    "TransactionListResponse",
]
